services:
  app:
    build: .
    container_name: managment_app
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}" # Maps host port to container port
    volumes:
      - .:/app # Mounts the current directory to /app in the container
      - /app/node_modules # Prevents overwriting node_modules

  db:
    image: postgres:18
    container_name: managment_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432" # Maps host port 5431 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql # Persists database data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: managment_pgadmin4
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PGADMIN_PORT}:80" # Maps host port 8080 to container port 80
  #   depends_on:
  #     - db
volumes:
  pgdata:
