import type { Metadata } from "next";

import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/contexts/AuthContext";
import { AppProvider } from "@/contexts/AppContext";
import { Toaster } from "sonner";

import { Afacad, Holtwood_One_SC, Geist_Mono, Geist, Roboto, Aclonica } from "./font";

import "./globals.css";

import NavBar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";
import { ModalRoot } from "@/components/modal/modal-root";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Geist.variable} ${Geist_Mono.variable} ${Afacad.variable} ${Holtwood_One_SC.variable} ${Roboto.variable} ${Aclonica.variable} antialiased
        px-1 text-size-default font-afacad bg-background relative max-w-[1700] m-auto
        `}
      >
        <AppProvider>
          <AuthProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
              <NavBar className="fixed left-2.5 right-2.5"></NavBar>

              <div className="max-w-[1700px] m-auto transition-all duration-300">{children}</div>

              <Footer></Footer>

              <Toaster position="top-center" />
              <ModalRoot />
            </ThemeProvider>
          </AuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
