version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: mangament_redis
    restart: always
    ports:
      - "6378:6379"

  cloudflare-tunnel:
    container_name: mangament_cloudflared_tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    env_file:
      - ./api/.env
    depends_on:
      - api

  ml-service:
    container_name: mangament_ml_service
    # THAY build BẰNG image TRÊN DOCKER HUB
    image: kozkhoa/mangament-server-ml-service:latest
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"

  api:
    container_name: mangament_api # Đã sửa dấu : thành _
    # THAY build BẰNG image TRÊN DOCKER HUB
    image: kozkhoa/mangament-server-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - ./api/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      - redis
    volumes:
      # BỎ MUNT CODE ĐÈ VÀO /app, CHỈ GIỮ LẠI THƯ MỤC UPLOADS ĐỂ LƯU TRỮ ẢNH MANGA
      - ../uploads:/app/uploads

  worker:
    container_name: mangament_worker # Đã sửa dấu : thành _
    # THAY build BẰNG image TRÊN DOCKER HUB
    image: kozkhoa/mangament-server-worker:latest
    build:
      context: ./api
      dockerfile: worker/Dockerfile
    restart: always
    env_file:
      - ./api/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      - redis
      - ml-service
      - api

  logs-db:
    container_name: mangament_logs_db
    image: mongo:8
    restart: always
    ports:
      - "27016:27017"
    env_file:
      - ./api/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mangament_logs_db_data:/data/db

volumes:
  mangament_logs_db_data:
