import Selection from "./selection";
import Nation from "@/types/nation";

export interface NationMultiSelectionProps {
  className?: string;

  defaultValue?: string | null;

  onChange?: (nation: Nation | null) => void;

  onReset?: (nation: Nation | null) => void;
}

const NATIONS = [
  "🇦🇫 Afghanistan",
  "🇦🇱 Albania",
  "🇩🇿 Algeria",
  "🇦🇩 Andorra",
  "🇦🇴 Angola",
  "🇦🇬 Antigua & Barbuda",
  "🇦🇷 Argentina",
  "🇦🇲 Armenia",
  "🇦🇺 Australia",
  "🇦🇹 Austria",
  "🇦🇿 Azerbaijan",
  "🇧🇸 Bahamas",
  "🇧🇭 Bahrain",
  "🇧🇩 Bangladesh",
  "🇧🇧 Barbados",
  "🇧🇾 Belarus",
  "🇧🇪 Belgium",
  "🇧🇿 Belize",
  "🇧🇯 Benin",
  "🇧🇹 Bhutan",
  "🇧🇴 Bolivia",
  "🇧🇦 Bosnia & Herzegovina",
  "🇧🇼 Botswana",
  "🇧🇷 Brazil",
  "🇧🇳 Brunei",
  "🇧🇬 Bulgaria",
  "🇧🇫 Burkina Faso",
  "🇧🇮 Burundi",
  "🇰🇭 Cambodia",
  "🇨🇲 Cameroon",
  "🇨🇦 Canada",
  "🇨🇻 Cabo Verde",
  "🇨🇫 Central African Republic",
  "🇹🇩 Chad",
  "🇨🇱 Chile",
  "🇨🇳 China",
  "🇨🇴 Colombia",
  "🇰🇲 Comoros",
  "🇨🇬 Republic of the Congo",
  "🇨🇩 DR Congo",
  "🇨🇷 Costa Rica",
  "🇭🇷 Croatia",
  "🇨🇺 Cuba",
  "🇨🇾 Cyprus",
  "🇨🇿 Czech Republic",
  "🇩🇰 Denmark",
  "🇩🇯 Djibouti",
  "🇩🇲 Dominica",
  "🇩🇴 Dominican Republic",
  "🇪🇨 Ecuador",
  "🇪🇬 Egypt",
  "🇸🇻 El Salvador",
  "🇬🇶 Equatorial Guinea",
  "🇪🇷 Eritrea",
  "🇪🇪 Estonia",
  "🇸🇿 Eswatini",
  "🇪🇹 Ethiopia",
  "🇫🇯 Fiji",
  "🇫🇮 Finland",
  "🇫🇷 France",
  "🇬🇦 Gabon",
  "🇬🇲 Gambia",
  "🇬🇪 Georgia",
  "🇩🇪 Germany",
  "🇬🇭 Ghana",
  "🇬🇷 Greece",
  "🇬🇩 Grenada",
  "🇬🇹 Guatemala",
  "🇬🇳 Guinea",
  "🇬🇼 Guinea-Bissau",
  "🇬🇾 Guyana",
  "🇭🇹 Haiti",
  "🇭🇳 Honduras",
  "🇭🇺 Hungary",
  "🇮🇸 Iceland",
  "🇮🇳 India",
  "🇮🇩 Indonesia",
  "🇮🇷 Iran",
  "🇮🇶 Iraq",
  "🇮🇪 Ireland",
  "🇮🇱 Israel",
  "🇮🇹 Italy",
  "🇯🇲 Jamaica",
  "🇯🇵 Japan",
  "🇯🇴 Jordan",
  "🇰🇿 Kazakhstan",
  "🇰🇪 Kenya",
  "🇰🇮 Kiribati",
  "🇰🇼 Kuwait",
  "🇰🇬 Kyrgyzstan",
  "🇱🇦 Laos",
  "🇱🇻 Latvia",
  "🇱🇧 Lebanon",
  "🇱🇸 Lesotho",
  "🇱🇷 Liberia",
  "🇱🇾 Libya",
  "🇱🇮 Liechtenstein",
  "🇱🇹 Lithuania",
  "🇱🇺 Luxembourg",
  "🇲🇬 Madagascar",
  "🇲🇼 Malawi",
  "🇲🇾 Malaysia",
  "🇲🇻 Maldives",
  "🇲🇱 Mali",
  "🇲🇹 Malta",
  "🇲🇭 Marshall Islands",
  "🇲🇷 Mauritania",
  "🇲🇺 Mauritius",
  "🇲🇽 Mexico",
  "🇫🇲 Micronesia",
  "🇲🇩 Moldova",
  "🇲🇨 Monaco",
  "🇲🇳 Mongolia",
  "🇲🇪 Montenegro",
  "🇲🇦 Morocco",
  "🇲🇿 Mozambique",
  "🇲🇲 Myanmar",
  "🇳🇦 Namibia",
  "🇳🇷 Nauru",
  "🇳🇵 Nepal",
  "🇳🇱 Netherlands",
  "🇳🇿 New Zealand",
  "🇳🇮 Nicaragua",
  "🇳🇪 Niger",
  "🇳🇬 Nigeria",
  "🇰🇵 North Korea",
  "🇲🇰 North Macedonia",
  "🇳🇴 Norway",
  "🇴🇲 Oman",
  "🇵🇰 Pakistan",
  "🇵🇼 Palau",
  "🇵🇦 Panama",
  "🇵🇬 Papua New Guinea",
  "🇵🇾 Paraguay",
  "🇵🇪 Peru",
  "🇵🇭 Philippines",
  "🇵🇱 Poland",
  "🇵🇹 Portugal",
  "🇶🇦 Qatar",
  "🇷🇴 Romania",
  "🇷🇺 Russia",
  "🇷🇼 Rwanda",
  "🇰🇳 Saint Kitts & Nevis",
  "🇱🇨 Saint Lucia",
  "🇻🇨 Saint Vincent & the Grenadines",
  "🇼🇸 Samoa",
  "🇸🇲 San Marino",
  "🇸🇹 São Tomé & Príncipe",
  "🇸🇦 Saudi Arabia",
  "🇸🇳 Senegal",
  "🇷🇸 Serbia",
  "🇸🇨 Seychelles",
  "🇸🇱 Sierra Leone",
  "🇸🇬 Singapore",
  "🇸🇰 Slovakia",
  "🇸🇮 Slovenia",
  "🇸🇧 Solomon Islands",
  "🇸🇴 Somalia",
  "🇿🇦 South Africa",
  "🇰🇷 South Korea",
  "🇸🇸 South Sudan",
  "🇪🇸 Spain",
  "🇱🇰 Sri Lanka",
  "🇸🇩 Sudan",
  "🇸🇷 Suriname",
  "🇸🇪 Sweden",
  "🇨🇭 Switzerland",
  "🇸🇾 Syria",
  "🇹🇼 Taiwan*",
  "🇹🇯 Tajikistan",
  "🇹🇿 Tanzania",
  "🇹🇭 Thailand",
  "🇹🇱 Timor-Leste",
  "🇹🇬 Togo",
  "🇹🇴 Tonga",
  "🇹🇹 Trinidad & Tobago",
  "🇹🇳 Tunisia",
  "🇹🇷 Turkey",
  "🇹🇲 Turkmenistan",
  "🇹🇻 Tuvalu",
  "🇺🇬 Uganda",
  "🇺🇦 Ukraine",
  "🇦🇪 United Arab Emirates",
  "🇬🇧 United Kingdom",
  "🇺🇸 United States",
  "🇺🇾 Uruguay",
  "🇺🇿 Uzbekistan",
  "🇻🇺 Vanuatu",
  "🇻🇦 Vatican City",
  "🇻🇪 Venezuela",
  "🇻🇳 Vietnam",
  "🇾🇪 Yemen",
  "🇿🇲 Zambia",
  "🇿🇼 Zimbabwe",
];

export default function NationSelection({ className, defaultValue = null, onChange, onReset }: NationMultiSelectionProps) {
  function handleChange(index: number | null) {
    onChange?.(index === null ? null : { name: NATIONS[index].slice(5), flag_icon: NATIONS[index].slice(0, 4) });
  }

  function handleReset(index: number | null) {
    handleChange(index);
  }

  return (
    <Selection
      className={className}
      label="Quốc gia "
      options={NATIONS}
      defaultIndex={defaultValue === null ? null : NATIONS.findIndex((nation) => nation.includes(defaultValue))}
      onChange={handleChange}
      onReset={onReset ? handleReset : undefined}
    />
  );
}
